#' Validate Active Connection Status Health
#'
#' Verifies an existing database connection object is valid and responsive.
#'
#' @param conn A DBI database connection object.
#' @return Logical scalar. TRUE if connection successfully responds, FALSE otherwise.
#' @export
utils_db_validate <- function(conn) {
  log_event("Starting utils_db_validate health check")

  if (is.null(conn)) {
    log_event("Connection object is NULL. Health check failed.")
    return(FALSE)
  }

  res <- tryCatch(
    utils_db_get_query(conn, "SELECT 1 AS health_check;"),
    error = function(e) {
      log_event(paste0("Database health query threw an error: ", e$message))
      NULL
    }
  )

  if (!is.null(res) && nrow(res) > 0 && res$health_check[1] == 1) {
    log_event("Database connection verified active and responsive.")
    return(TRUE)
  }

  log_event(
    "Database health response invalid or unparseable. Health check failed."
  )
  return(FALSE)
}

#' Execute Code Block under Database Connection Retries
#'
#' Safe transactional wrapper that catches dropped database connections and executes
#' up to 3 automatic re-evaluations before failure.
#'
#' @param expr Expression block. The sequence of database operations to run.
#' @return Output context generated by the evaluation expression block.
#' @export
with_db_retry <- function(expr) {
  log_event("Starting with_db_retry block evaluation")

  max_attempts <- 3
  attempt <- 1

  while (attempt <= max_attempts) {
    res <- tryCatch(
      {
        eval(expr)
      },
      error = function(e) {
        if (
          grepl(
            "connection|timeout|communication link failure",
            tolower(e$message)
          )
        ) {
          log_event(
            sprintf(
              "DB Connection issue caught: '%s'. Attempt %d of %d. Retrying...",
              e$message,
              attempt,
              max_attempts
            )
          )
          return(structure(list(message = e$message), class = "db_retry_error"))
        }
        log_event(paste0(
          "Non-connection structural bug encountered: ",
          e$message
        ))
        stop(e) # rethrow structural logic bugs immediately
      }
    )

    if (!inherits(res, "db_retry_error")) {
      log_event("Expression successfully evaluated without connection errors.")
      return(res)
    }

    attempt <- attempt + 1
    if (attempt <= max_attempts) {
      backoff_delay <- 0.5 * attempt
      log_event(sprintf(
        "Backing off for %0.2f seconds before execution re-attempt.",
        backoff_delay
      ))
      Sys.sleep(backoff_delay)
    }
  }

  log_event(
    "Database operations failed. Connection retry registry threshold exhausted."
  )
  stop("Database connection attempts exhausted after 3 attempts.")
}
